name: On PR

# On pull_request, we:
# * create backport labels if it is against main, only when the PR is opened/reopened

on:
  pull_request:

jobs:

  populate-labels:
    name: Populate labels
    if: github.base_ref == 'main' && (github.event.action == 'opened' || github.event.action == 'reopened')
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/populate-labels.yaml@main
    secrets: inherit
    with:
      track_file_path: ".github/automatic_backport_tracks.yaml"
      label_prefix: "backport "

  app-tests:
    name: Application tests
    uses: ./.github/workflows/test_application.yaml

  on-pull-request:
    needs: [app-tests]
    # Build the rock only if the application tests passed or were skipped
    # (i.e. no application changes in this PR).
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/get-rocks-modified-and-build-scan-test-publish.yaml@main
    permissions:
      pull-requests: read
    secrets: inherit
