name: On PR

on:
  pull_request:

jobs:

  app-tests:
    name: Application tests
    uses: ./.github/workflows/test_application.yaml

  on-pull-request:
    needs: [app-tests]
    # Build the rock only if the application tests passed or were skipped
    # (i.e. no application changes in this PR).
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/get-rocks-modified-and-build-scan-test-publish.yaml@main
    permissions:
      pull-requests: read
    secrets: inherit
