name: On Push

on:
  push:
    branches:
    - main
    - track/**

jobs:

  app-tests:
    name: Application tests
    uses: ./.github/workflows/test_application.yaml

  on-push:
    needs: [app-tests]
    # Build the rock only if the application tests passed or were skipped
    # (i.e. no application changes in this push).
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/get-rocks-modified-and-build-scan-test-publish.yaml@main
    permissions:
      pull-requests: read
    secrets: inherit
